---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define chrony_packages.
  set_fact:
    chrony_packages: "{{ __chrony_packages | list }}"
  when: chrony_packages is not defined

# Setup/install tasks.
- include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure chrony has selected state and enabled on boot.
  service:
    name: "{{ chrony_service }}"
    state: "{{ chrony_state }}"
    enabled: true
